"""empty message

Revision ID: 5dc06889a034
Revises: 932d8d1a67f4
Create Date: 2023-09-25 21:30:27.904789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc06889a034'
down_revision: Union[str, None] = '932d8d1a67f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.String(), nullable=False))
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'login')
    # ### end Alembic commands ###
